### ISSUE TITLE
JPG压缩功能优化建议

### ISSUE THREAD

**Issue by toyo2333** [richhost/pixzip#10]
建议使用MozJPEG来压缩JPG图片

我在用的其他几个产品imagine 、squoosh.app等的jpg压缩默认都使用的是是这个。

不知道你的新版本什么时候出来，希望老版本能更新一个版本支持。

谢谢

**Comment by richhost** [comment]
感谢反馈，MozJPEG 是非常出色的 JPEG 压缩算法，已在 1.x 版本中使用。新版本已进入倒计时阶段，很快就会提供下载。

**Comment by toyo2333** [comment]
> 感谢反馈，MozJPEG 是非常出色的 JPEG 压缩算法，已在 1.x 版本中使用。新版本已进入倒计时阶段，很快就会提供下载。
感谢你回复，我可能没说清楚。

我的意思是经过我测试对比，同一个JPEG图片，发现按相同的品质进行压缩，压后的size 你比imagine 、squoosh.app的都大，换一种方法，如果尝试压到同样的size，最终图片你的jpg更模糊。我测过很多次。

squoosh.app提供了两个JGP的压缩选项 ，还有一个是BroswerJPEG，那个压出来的size和你一样。

所以我怀疑是你没有用MozJPEG，或者是有bug，才来反馈这个问题的。

**Comment by richhost** [comment]
感谢你提供详细的说明。1.x 确实存在此问题，2.0 版本会解决。

**Comment by toyo2333** [comment]
> 感谢你提供详细的说明。1.x 确实存在此问题，2.0 版本会解决。

再提一个，希望新版本支持“移除exif”的选项，压缩的时候把隐私信息去除。

**Comment by richhost** [comment]
感谢你的提议，[V2.1.0](https://github.com/richhost/pixzip/releases/tag/v2.1.0) 已包含此功能，故关闭。
