### ISSUE TITLE
无法压缩的BUG

### ISSUE THREAD

**Issue by kofzhanganguo** [richhost/pixzip#13]
![image](https://github.com/richhost/pixzip/assets/32073931/b41b5151-2a96-4c92-a9ef-991da3df26eb)
![image](https://github.com/richhost/pixzip/assets/32073931/ef3999ee-3532-4319-bd04-e227c1668877)
当以原始格式压缩，然后不添加任何文件后缀，压缩就报错，无法压缩，也就是说，这样就无法替原始文件。
![image](https://github.com/richhost/pixzip/assets/32073931/409d29c0-0e20-45a4-a77f-df392000e6d6)
然后就是文件夹的拖入压缩问题，一次只能拖入一个文件夹，不能多个文件夹同时拖入后压缩，希望早点解决这个问题。
![image](https://github.com/richhost/pixzip/assets/32073931/a36b7f52-f07d-4962-ad16-1e37dfc32b8b)
还有就是嵌套的文件夹问题，文件夹里面还有个文件夹，然后子文件夹中有图片文件，这样就无法进行文件夹的拖入后压缩，也就是只能从一个包含图片文件夹拖入后，才可以压缩，从主文件夹拖入到软件中，软件无法导入，必须只有图片的文件夹才可以进行导入。
目前就是这些BUG，希望早点能修复。

**Comment by richhost** [comment]
已修复 [v2.12](https://github.com/richhost/pixzip/releases/tag/v2.1.2)
