### ISSUE TITLE
遇到大GIF 文件程序闪退

### ISSUE THREAD

**Issue by Jackxwb** [richhost/pixzip#17]
样本文件
![1701484342884](https://github.com/richhost/pixzip/assets/34720403/3a817de1-a973-41bd-81d9-b403048d3e38)
![image](https://github.com/richhost/pixzip/assets/34720403/d53ec4fb-aa19-48ed-879b-5b03923a88ca)
```
大小：	6, 731, 864 字节
MD5：	5E80C6E4FA627EF7972BE759D0A39EF1
SHA1：	65FBE983387428D31508536E16E72557FFEF3935
CRC32：566BD78F
```
拖动到列表自动处理，转圈转一会，程序就会闪退

**Comment by richhost** [comment]
已修复闪退问题，具体原因请查看更新日志：https://github.com/richhost/pixzip/releases/tag/v2.1.5
若后续上游修复，会立即适配，故关闭。
