### ISSUE TITLE
优化建议：转换后体积增加时用向上箭头表示

### ISSUE THREAD

**Issue by Tsubamei** [richhost/pixzip#20]
![PixPin_2024-05-22_09-51-26](https://github.com/richhost/pixzip/assets/61179776/9be19383-2a66-4c5a-b847-108aa8ed98d1)
转换后文件体积增大时，目前是显示的“向下箭头+负数”的形式
希望能优化成“向上箭头+正数+红色”的形式以作区分

**Comment by richhost** [comment]
感谢建议，请下载最新版使用： https://github.com/richhost/pixzip/releases
