### ISSUE TITLE
希望能支持宽高按比例缩放

### ISSUE THREAD

**Issue by Gnaix-39** [richhost/pixzip#21]
比如我希望输出2倍图、3倍图，或者是0.5倍图、0.33倍图
面对批量需要产出倍图的场景，目前的pixzip只能一个一个放进去人工计算对应宽高
以及如果有比例输出的话就自然会有保持纵横比的勾选项
这样输入其中一个宽高，就可以自动按照原图已有宽高，锁比例输出

如果出了我会购买pro许可的😉

**Comment by richhost** [comment]
感谢你的建议，最近正在构思这方面的功能。我自己在做开发的时候也有类似的需求，所以准备面向前端工程师的使用场景做个特定的模式，敬请期待。

**Comment by richhost** [comment]
付费版本已提供相关功能，故关闭该 issues。欢迎在 [官方网站](https://pixzip.cutepuppy.tech/) 查看。♥️
